### ISSUE TITLE
completer uses 'IPython.utils.rlineimpl' which has been removed.

### ISSUE THREAD

**Issue by ivanov** [jupyter/jupyter_console#110]
over on https://github.com/ipython/ipython/pull/9991, the rlineimpl has been removed, but jupyter_console relied on it.

As it stands, `jupyter console` does not work with ipython master and will throw this 

```
Traceback (most recent call last):
  File ".../bin/jupyter-console", line 9, in <module>
    load_entry_point('jupyter-console==5.1.0.dev0', 'console_scripts', 'jupyter-console')()
  File ".../lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File ".../lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File ".../lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File ".../lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File ".../lib/python3.5/site-packages/jupyter_console/app.py", line 26, in <module>
    from jupyter_console.ptshell import ZMQTerminalInteractiveShell
  File ".../lib/python3.5/site-packages/jupyter_console/ptshell.py", line 28, in <module>
    from .completer import ZMQCompleter
  File ".../lib/python3.5/site-packages/jupyter_console/completer.py", line 16, in <module>
    import IPython.utils.rlineimpl as readline
```

cc @takluyver and @willingc

**Comment by takluyver** [comment]
#111 should fix this.
