### ISSUE TITLE
jupyter console fails loading on Mac OS X

### ISSUE THREAD

**Issue by avigan** [jupyter/jupyter_console#144]
I am trying to run ```jupyter console``` on Mac OS X (10.13.1) after an install of Python using anaconda and here is what I get:

```python
[17:00] ~ > jupyter console
[IPKernelApp] WARNING | Config option `autoindent` not recognized by `ZMQInteractiveShell`.
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x10b2d1400>)
Traceback (most recent call last):
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 265, in enter_eventloop
    self.eventloop(self)
  File "/Users/avigan/anaconda3/lib/python3.6/site-packages/ipykernel/eventloops.py", line 277, in loop_cocoa
    show.mainloop()
AttributeError: 'function' object has no attribute 'mainloop'
Jupyter console 5.2.0

Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 18:10:31)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
```

It does open a prompt at the end, but the problem is that I get weird behaviours in GUIs (e.g. in matplotlib) started from this prompt.

**Comment by garciparedes** [comment]
I'm having the same problem right now.
