### ISSUE TITLE
Promptkit still crashing

### ISSUE THREAD

**Issue by ocehugo** [jupyter/jupyter_console#152]
Hi I believe this is related to #123 and the new promptkit, and remnant of a problem reported in ipython#10381.

I do not have the ipython#10381 problem anymore, but a similar one: Completing paths after pressing tab crash the session in jupyter_console.

The problem is I coudn't find a way to easily reproduce and the trace is not always the same:

Sometimes is this:
``` python
In [119]: cd ~/mycode/aResource temporarily unavailable (bundled/zeromq/src/signaler.cpp:301)
Abort trap: 6
~ exited  $ [IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

and others:
Code:
```python
In [101]: cd ~/mycode/ar
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/app.py", line 155, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 508, in mainloop
    self.interact()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 492, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 440, in prompt_for_code
    reset_current_buffer=True)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 415, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 159, in run
    t()
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 111, in get_completions
    cursor_pos=document.cursor_position
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/completer.py", line 39, in complete_request
    msg = self.client.shell_channel.get_msg(timeout=self.timeout)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 55, in get_msg
    return self._recv()
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 43, in _recv
    return self.session.deserialize(smsg)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/session.py", line 923, in deserialize
    raise ValueError("Invalid Signature: %r" % signature)
ValueError: Invalid Signature: b'6746766c7229a866681e5d3d18106349c37caa05a5216f73cde4f96fc24f06f4'
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin

    inputstream.feed(data)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 398, in feed
    self._input_parser.send(c)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 307, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/terminal/vt100_input.py", line 340, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 1048, in feed_key
    cli.input_processor.process_keys()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/key_binding/input_processor.py", line 219, in process_keys
    self._process_coroutine.send(key_press)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/key_binding/input_processor.py", line 176, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/key_binding/input_processor.py", line 247, in _call_handler
    handler.call(event)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/key_binding/registry.py", line 61, in call
    return self.handler(event)
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 367, in _
    more, indent = self.check_complete(d.text)
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 454, in check_complete
    return self.handle_is_complete_reply(msg_id, timeout=self.kernel_is_complete_timeout)
  File "/usr/local/lib/python3.6/site-packages/jupyter_console/ptshell.py", line 615, in handle_is_complete_reply
    msg = self.client.shell_channel.get_msg(block=True, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 55, in get_msg
    return self._recv()
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/blocking/channels.py", line 42, in _recv
    ident,smsg = self.session.feed_identities(msg)
  File "/usr/local/lib/python3.6/site-packages/jupyter_client/session.py", line 844, in feed_identities
    idx = msg_list.index(DELIM)
ValueError: b'<IDS|MSG>' is not in list
```

Versions:

Python 3.6.4
jupyter-client 5.2.2
jupyter-console 5.2.0
jupyter-core 4.4.0
promptkit-1.0.15

**Comment by takluyver** [comment]
The first bit at least appears to be coming from ZMQ - @minrk , any ideas?

**Comment by tom-saildrone** [comment]
I'm having a [potentially similar issue](https://github.com/jupyter/notebook/issues/3762), possibly related?

**Comment by mosfiqur-rahman** [comment]
@ocehugo  Hi, I'm also having the same issue. Could you find any solution or workaround for the issue?

**Comment by Chaoste** [comment]
Hi, I'm facing the same issue.
Sometimes the process stops during some long experiments which is very critical for me. Any updates on this? Are there some debug information, you require for better investigations?

Greetings,
Thomas

**Comment by ocehugo** [comment]
@mosfiqur-rahman 

Its been a while since I didn't face this problem.

Don't know if related, but I'm using a different system and packaging [based on pyenv/miniconda]. It's kept updated on a monthly basis with upstream/pip packages. Maybe an update can get rid of it for you perhaps!?
