### ISSUE TITLE
History not handled properly in `jupyter_console`

### ISSUE THREAD

**Issue by pprzetacznik** [jupyter/jupyter_console#157]
We can read in the documentation about supporting history: http://jupyter-client.readthedocs.io/en/stable/messaging.html#history
```
content = {
  # A list of 3 tuples, either:
  # (session, line_number, input) or
  # (session, line_number, (input, output)),
  # depending on whether output was False or True, respectively.
  'history' : list,
}
```

It's all ok when I send `(session, line_number, input)` to the Jupyter but when I send `(session, line_number, (input, output))` I receive an error:
```
Traceback (most recent call last):
  File "/home/aaa/.virtualenvs/testenv1/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 273, in __init__
    self.init_prompt_toolkit_cli()
  File "/home/aaa/.virtualenvs/testenv1/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 390, in init_prompt_toolkit_cli
    cell = cast_unicode_py2(cell.rstrip())
AttributeError: 'list' object has no attribute 'rstrip'
```

I've checked the code in ptshell.py file: https://github.com/jupyter/jupyter_console/blob/master/jupyter_console/ptshell.py#L400
and there's implementation of history handling which uses rstrip but I can't see supporting of `(input, output)` format of history messages:
```
         @kbmanager.registry.add_binding(Keys.ControlZ, filter=Condition(lambda cli: suspend_to_background_supported()))
        def _(event):
            event.cli.suspend_to_background()

        # Pre-populate history from IPython's history database
        history = InMemoryHistory()
        last_cell = u""
        for _, _, cell in self.history_manager.get_tail(self.history_load_length,
                                                        include_latest=True):
            # Ignore blank lines and consecutive duplicates
            cell = cast_unicode_py2(cell.rstrip())
            if cell and (cell != last_cell):
                history.append(cell)
```

Am I missing something? Does support of `(input, output)` actually working?

**Comment by pprzetacznik** [comment]
This issue is orchestrated by `output` field sent in request message.
```
  # If True, also return output history in the resulting dict.
  'output' : bool,
```
This is solved right now.
