### ISSUE TITLE
Jupyter console crashes on Python 3.7

### ISSUE THREAD

**Issue by dschrempf** [jupyter/jupyter_console#163]
Jupyter console crashes since a recent updae to Python 3.7.

    python 3.7.0
    jupyter version 4.4.0
    jupyter console version 5.2.0
    python-tornado 5.1.0
    python-pyzmq 17.1.0-1

    python -c "import IPython; print(IPython.sys_info())"
    {'commit_hash': '<not found>',
     'commit_source': '(none found)',
     'default_encoding': 'UTF-8',
     'ipython_path': '/usr/lib/python3.7/site-packages/IPython',
     'ipython_version': '6.5.0',
     'os_name': 'posix',
     'platform': 'Linux-4.17.12-arch1-1-ARCH-x86_64-with-arch',
     'sys_executable': '/usr/bin/python',
     'sys_platform': 'linux',
     'sys_version': '3.7.0 (default, Jul 15 2018, 10:44:58) \n[GCC 8.1.1 20180531]'}

    jupyter console
    
    ERROR:tornado.general:Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
        callback(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
        self.pre_handler_hook()
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
        self.saved_sigint_handler = signal(SIGINT, default_int_handler)
      File "/usr/lib/python3.7/signal.py", line 47, in signal
        handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
    ValueError: signal only works in main thread
    ERROR:tornado.general:Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
        self._handle_recv()
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
        callback(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
        self.pre_handler_hook()
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
        self.saved_sigint_handler = signal(SIGINT, default_int_handler)
      File "/usr/lib/python3.7/signal.py", line 47, in signal
        handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
    ValueError: signal only works in main thread
    Traceback (most recent call last):
      File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
        app.launch_new_instance()
      File "/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
        app.start()
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 477, in start
        ioloop.IOLoop.instance().start()
      File "/usr/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
        self.asyncio_loop.run_forever()
      File "/usr/lib/python3.7/asyncio/base_events.py", line 510, in run_forever
        raise RuntimeError('This event loop is already running')
    RuntimeError: This event loop is already running
    ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f11c7fb8a60>)
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 536, in <lambda>
        self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
        self._handle_recv()
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
        self._run_callback(callback, msg)
      File "/usr/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
        callback(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
        return self.dispatch_shell(stream, msg)
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
        self.pre_handler_hook()
      File "/usr/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
        self.saved_sigint_handler = signal(SIGINT, default_int_handler)
      File "/usr/lib/python3.7/signal.py", line 47, in signal
        handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
    ValueError: signal only works in main thread
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 323, in init_kernel_info
        reply = self.client.get_shell_msg(timeout=1)
      File "/usr/lib/python3.7/site-packages/jupyter_client/client.py", line 77, in get_shell_msg
        return self.shell_channel.get_msg(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    _queue.Empty

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/bin/jupyter-console", line 5, in <module>
        app.main()
      File "/usr/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
        app.initialize(argv)
      File "<decorator-gen-116>", line 2, in initialize
      File "/usr/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
        return method(app, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/jupyter_console/app.py", line 141, in initialize
        self.init_shell()
      File "/usr/lib/python3.7/site-packages/jupyter_console/app.py", line 114, in init_shell
        client=self.kernel_client,
      File "/usr/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
        inst = cls(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 272, in __init__
        self.init_kernel_info()
      File "/usr/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 326, in init_kernel_info
        raise RuntimeError("Kernel didn't respond to kernel_info_request")
    RuntimeError: Kernel didn't respond to kernel_info_request

**Comment by dschrempf** [comment]
Problem has been solved (although I do not know by whom, or how).

**Comment by codl** [comment]
updating ipykernel to 4.8.2 did it for me, i think. it seems arch linux's ipykernel package [had been outdated for some time](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/python-ipykernel)

**Comment by GabeDottl** [comment]
+1 

`pip install --upgrade ipykernel `

fixed it for me on MacOS as wel - thanks @codl !

**Comment by femiaiyeku** [comment]
Upgrading ipykernel worked for me
conda upgrade ipykernel

**Comment by gsdobrev** [comment]
"conda update ipykernel" worked for me. The old version was 4.6.1. Win8.1

**Comment by UrbanScientist** [comment]
This fix worked for me. Thanks! 

"pip install --upgrade ipykernel"

**Comment by plavine8183** [comment]
no dice

Collecting ipykernel
  Downloading https://files.pythonhosted.org/packages/d8/b0/f0be5c5ab335196f5cce96e5b889a4fcf5bfe462eb0acc05cd7e2caf65eb/ipykernel-5.1.0-py3-none-any.whl (113kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 122kB 2.8MB/s 
Requirement already satisfied, skipping upgrade: jupyter-client in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipykernel) (5.2.3)
Requirement already satisfied, skipping upgrade: traitlets>=4.1.0 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipykernel) (4.3.2)
Requirement already satisfied, skipping upgrade: tornado>=4.2 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipykernel) (5.0.2)
Requirement already satisfied, skipping upgrade: ipython>=5.0.0 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipykernel) (6.3.1)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from jupyter-client->ipykernel) (17.0.0)
Requirement already satisfied, skipping upgrade: jupyter-core in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from jupyter-client->ipykernel) (4.4.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from jupyter-client->ipykernel) (2.7.2)
Requirement already satisfied, skipping upgrade: ipython-genutils in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from traitlets>=4.1.0->ipykernel) (0.2.0)
Requirement already satisfied, skipping upgrade: decorator in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from traitlets>=4.1.0->ipykernel) (4.2.1)
Requirement already satisfied, skipping upgrade: six in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from traitlets>=4.1.0->ipykernel) (1.11.0)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (39.0.1)
Requirement already satisfied, skipping upgrade: pygments in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (2.2.0)
Requirement already satisfied, skipping upgrade: prompt-toolkit<2.0.0,>=1.0.15 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (1.0.15)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (0.11.1)
Requirement already satisfied, skipping upgrade: simplegeneric>0.8 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (0.8.1)
Requirement already satisfied, skipping upgrade: pexpect; sys_platform != "win32" in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (4.4.0)
Requirement already satisfied, skipping upgrade: backcall in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (0.1.0)
Requirement already satisfied, skipping upgrade: pickleshare in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel) (0.7.4)
Requirement already satisfied, skipping upgrade: wcwidth in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=5.0.0->ipykernel) (0.1.7)
Requirement already satisfied, skipping upgrade: parso==0.1.1 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel) (0.1.1)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in /root/.virtualenvs/ZIPLINE/lib/python3.5/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.0.0->ipykernel) (0.5.2)
Installing collected packages: ipykernel
  Found existing installation: ipykernel 4.8.2
    Uninstalling ipykernel-4.8.2:
      Successfully uninstalled ipykernel-4.8.2
Successfully installed ipykernel-5.1.0


After upgrade:

ERROR:asyncio:Exception in callback BaseAsyncIOLoop._handle_events(6, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(6, 1)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 102, in _handle_events
    handler_func(fileobj, events)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 252, in accept_handler
    callback(connection, address)
  File "/usr/local/lib/python3.6/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
    do_handshake_on_connect=False)
  File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 551, in ssl_wrap_socket
    context = ssl_options_to_context(ssl_options)
  File "/usr/local/lib/python3.6/site-packages/tornado/netutil.py", line 526, in ssl_options_to_context
    context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
ssl.SSLError: [SSL] PEM lib (_ssl.c:3358)

**Comment by devika-28** [comment]
pip install --upgrade ipykernel will upgrade your kernel and it will solve the problem.

**Comment by NathanLewis** [comment]
I'm having this problem in August 2019. I have tried downgrading to ipykernel 4.8.2 from version 5.1.1 and it still breaks. Any other thoughts on how to fix this?

**Comment by NathanLewis** [comment]
I finally managed to get around the error by installing python3.6 in a docker container and running it from there. python3.5 was too low a version and python3.7.3 appears to be too high. I think this issue should be reopened.

**Comment by NathanLewis** [comment]
This looks like the reason for the issue:
../python3.6/site-packages/ipykernel_launcher.py:15: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.

**Comment by NathanLewis** [comment]
I also get 
Collecting pyparsing==2.4.1 (from -r requirements.txt (line 98))
  Could not find a version that satisfies the requirement pyparsing==2.4.1 (from -r requirements.txt (line 98)) (from versions: 1.4.6, 1.4.7, 1.4.8, 1.4.11, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1.1, 2.4.2a1, 2.4.2)
No matching distribution found for pyparsing==2.4.1 (from -r requirements.txt (line 98))

I also had to change pyparsing to 2.4.2

**Comment by fjprobos** [comment]
Same issue here with python 3.7 and ipykernel 5.1.2.

```log
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
```

**Comment by Aditya-Singh-SSJ2** [comment]
I used pip install --upgrade ipykernel  and after installing all sorts of stuff, problem remained the same for me with the 'pip install jupyter' on Windows CMD.

**Comment by Alexander-Serov** [comment]
Same problem with `ipykernel 5.1.3`.

**Comment by Alexander-Serov** [comment]
If there is no other active issue on this topic, can someone reopen this one??

**Comment by brando90** [comment]
> +1
> 
> `pip install --upgrade ipykernel `
> 
> fixed it for me on MacOS as wel - thanks @codl !

that command did something...but my jupyter notebook still can't find my modules. Might that be realted to this issue?

Jupyter thinks its using 3.7.4 while terminal is using 3.7.5 (I would have expected them to match). Here is other stuff I tried without success:

```
(automl) brandomiranda~ ❯ pip3 install --force-reinstall upgrade jupyter
Collecting upgrade
  Could not find a version that satisfies the requirement upgrade (from versions: )
No matching distribution found for upgrade
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(automl) brandomiranda~ ❯ pip install --upgrade pip
Requirement already up-to-date: pip in ./miniconda3/envs/automl/lib/python3.7/site-packages (19.3.1)
```

related issue: https://github.com/jupyter/notebook/issues/4439

**Comment by jpthirumalai** [comment]
`pip install --upgrade ipykernel` 
This worked - made the kernel up again - "jupyter notebook"

**Comment by maalaria** [comment]
I got a similar error when I run jobs in parallel, but not otherwise. I am using ipykernel 5.2.0, python 3.7.7 on macOS Catalina.

The output is:
```
Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File ".../lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
        callback(*args, **kwargs)
      File ".../lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 203, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File ".../lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 317, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File ".../lib/python3.7/site-packages/jupyter_client/session.py", line 927, in deserialize
        raise ValueError("Duplicate Signature: %r" % signature)
    ValueError: Duplicate Signature: b'27883bcc298dc7f7334b2423f84a3bd7982fa8c96edd38240a8da730262e0f4f'
```

**Comment by praveenpno** [comment]
Issue "ERROR:tornado.general:Uncaught exception in ZMQStream callback"
The above error got resolved in windows by running the command "pip install --upgrade ipykernel" and restarting the kernel. Thanks team

**Comment by ClimberBear** [comment]
For me, the upgrade did the trick. For additional info, the original kernel was downgraded when I installed `google-colab` locally.

**ERROR: google-colab 1.0.0 has requirement ipykernel~=4.6.0, but you'll have ipykernel 5.3.4 which is incompatible.**
Installing collected packages: ipykernel
  Attempting uninstall: ipykernel
    Found existing installation: ipykernel 4.6.1
    Uninstalling ipykernel-4.6.1:
      Successfully uninstalled ipykernel-4.6.1
Successfully installed ipykernel-5.3.4

**Comment by Lawrence-Krukrubo** [comment]
Thanks! the `pip install --upgrade ipykernel` worked!
