### ISSUE TITLE
jupyter console will not open

### ISSUE THREAD

**Issue by brunobeltran** [jupyter/jupyter_console#18]
Was hoping to try out the console, but it does not appear to run in its current state.
```
$ sudo pip3 install -U jupyter_console
Requirement already up-to-date: jupyter-console in /usr/local/lib/python3.4/dist-packages
Cleaning up...
$ jupyter console
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 2, in <module>
    from jupyter_console import app
  File "/usr/local/lib/python3.4/dist-packages/jupyter_console/app.py", line 70, in <module>
    class ZMQTerminalIPythonApp(TerminalIPythonApp, JupyterApp, JupyterConsoleApp):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

If it matters, I currently also have ipython installed (at 3.2.1). Everything else is completely updated though.

**Comment by minrk** [comment]
It should have barfed on install, since IPython 3 won't work. I believe this is fixed by ipykernel 4.0.2. You need `pip3 install --pre --upgrade jupyter-console`. What do you get from `pip list`?

**Comment by brunobeltran** [comment]
Hmm, ipykernel is already at 4.0.2. Also, the error is the same if I install for python 2.7.
```
beautifulsoup4 (4.3.2)
Bottleneck (1.0.0)
brewer2mpl (1.4.1)
Brlapi (0.6.2)
chardet (2.3.0)
colorama (0.3.2)
decorator (4.0.0)
ggplot (0.6.5)
html5lib (0.999)
husl (4.0.2)
ipykernel (4.0.2)
ipython (3.2.1)
ipython-genutils (0.1.0)
Jinja2 (2.7.3)
jsonschema (2.5.1)
jupyter-client (4.0.0)
jupyter-console (4.0.0)
jupyter-core (4.0.2)
louis (2.5.3)
lxml (3.4.0)
MarkupSafe (0.23)
matplotlib (1.4.2)
nose (1.3.4)
numexpr (2.4.3)
numpy (1.9.2)
pandas (0.16.2)
path.py (7.4)
patsy (0.3.0)
pexpect (3.3)
pickleshare (0.5)
Pillow (2.6.1)
pip (1.5.6)
ptyprocess (0.5)
pyflakes (0.8.1)
Pygments (2.0.1)
pygobject (3.14.0)
pyparsing (2.0.3)
python-apt (0.9.3.11)
python-dateutil (2.4.2)
python-debian (0.1.27)
pytz (2015.4)
pyxdg (0.25)
PyYAML (3.11)
pyzmq (14.4.0)
requests (2.4.3)
scikit-learn (0.16.1)
scipy (0.15.1)
seaborn (0.6.0)
setuptools (5.5.1)
simplegeneric (0.8.1)
six (1.9.0)
statsmodels (0.6.1)
tables (3.1.1)
terminado (0.5)
Theano (0.7.0)
tornado (4.2.1)
traitlets (4.0.0)
urllib3 (1.9.1)
virtualenv (1.11.6)
wheel (0.24.0)
```

**Comment by minrk** [comment]
Hm, that appears to be a bug in super-old pip. Can you:

```bash
pip install --upgrade setuptools pip
pip uninstall ipykernel
pip install ipykernel
```

and see if it behaves differently? IPython 3.2.1 definitely does not satisfy the dependencies of ipykernel 4.0.2.

**Comment by brunobeltran** [comment]
That appears to have solved the problem! Must have been one of Debian's distutils installs interfering?

**Comment by nathanielng** [comment]
FYI. this also worked for me (pip install --upgrade setuptools pip; pip uninstall ipykernel; pip install ipykernel). My system: ipykernel-4.2.2, ipython-4.0.3, Anaconda Python/Mac OS X (Yosemite).
