### ISSUE TITLE
Notebook Console doesnt open after change c.ZMQTerminalInteractiveShell.include_other_output = True

### ISSUE THREAD

**Issue by schlesserr** [jupyter/jupyter_console#250]
When a change the option to true i cant run console

Shutting down kernel
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<ZMQTerminalInteractiveShell.handle_external_iopub() done, defined at /home/schlesser/Python/redis/.venv/lib/python3.9/site-packages/jupyter_console/ptshell.py:835> exception=RuntimeError("There is no current event loop in thread 'asyncio_0'.")>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "/home/schlesser/Python/redis/.venv/lib/python3.9/site-packages/jupyter_console/ptshell.py", line 839, in handle_external_iopub
    poll_result = await loop.run_in_executor(
  File "/usr/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/schlesser/Python/redis/.venv/lib/python3.9/site-packages/zmq/_future.py", line 306, in poll
    f = p.poll(timeout)
  File "/home/schlesser/Python/redis/.venv/lib/python3.9/site-packages/zmq/_future.py", line 61, in poll
    future = self._Future()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'asyncio_0'.

Any thoughts?

**Comment by thalesnunes** [comment]
Same here :(.
My setup:
OS: Arch Linux
Kernel: 5.13.19
Python 3.9.7
Jupyter console 6.4.0
IPython 7.28

**Comment by doronbehar** [comment]
> I got it working by following #251 . Hope it helps someone!

The error in https://github.com/jupyter/jupyter_console/issues/251 seems different to me from the error reported here. I also experience the same issue reported here, and the patch from https://github.com/jupyter/jupyter_console/pull/244 didn't help me :(.
