### ISSUE TITLE
Jupiter console crashes on Python 3.10

### ISSUE THREAD

**Issue by pietvo** [jupyter/jupyter_console#255]
Jupiter console crashes on Python 3.10. The reason is that `asyncio.wait` (called in `ptshell.py`) no longer has a `loop` parameter.

```
% jupyter-3.10 console
Jupyter console 6.4.0

Python 3.10.0 (default, Nov 12 2021, 11:30:27) [Clang 11.0.3 (clang-1103.0.32.62)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.28.0 -- An enhanced Interactive Python. Type '?' for help.
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/jupyter-console", line 33, in <module>
    sys.exit(load_entry_point('jupyter-console==6.4.0', 'console_scripts', 'jupyter-console')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_console/app.py", line 148, in start
    self.shell.mainloop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_console/ptshell.py", line 664, in mainloop
    main_task = asyncio.wait(tasks, loop=loop, return_when=asyncio.FIRST_COMPLETED)
TypeError: wait() got an unexpected keyword argument 'loop'
sys:1: RuntimeWarning: coroutine 'ZMQTerminalInteractiveShell.interact' was never awaited
```

**Comment by NeilGirdhar** [comment]
Duplicate of https://github.com/jupyter/jupyter_console/issues/245?

**Comment by pietvo** [comment]
Yes, that looks the same. I'm closing this one.
