### ISSUE TITLE
Cannot run jupyter-console

### ISSUE THREAD

**Issue by Tiko7454** [jupyter/jupyter_console#268]
It worked for me, but when I updated it, I have this error

Traceback (most recent call last):
  File "/sbin/jupyter-console", line 5, in <module>
    from jupyter_console.app import main
  File "/usr/lib/python3.10/site-packages/jupyter_console/app.py", line 25, in <module>
    from jupyter_console.ptshell import ZMQTerminalInteractiveShell
  File "/usr/lib/python3.10/site-packages/jupyter_console/ptshell.py", line 35, in <module>
    from .completer import ZMQCompleter
  File "/usr/lib/python3.10/site-packages/jupyter_console/completer.py", line 10, in <module>
    from jupyter_client.utils import run_sync
ImportError: cannot import name 'run_sync' from 'jupyter_client.utils' (/home/tiko7454/.local/lib/python3.10/site-packages/jupyter_client/utils.py)

I wanted to find a file which containes run_sync function to link it from /usr/lib/python3.10/site-packages/jupyter_console/completer.py file but I couldn't

**Comment by davidbrochart** [comment]
`run_sync` [exists in jupyter-client](https://github.com/jupyter/jupyter_client/blob/7aed569f2686aac5b07a7d3fc2ae860b4e82eb5a/jupyter_client/utils.py#L11).
Which version of jupyter-client do you have?

**Comment by Tiko7454** [comment]
7.1.2-1 (I installed it with pacman)
