### ISSUE TITLE
BUG: Resource temporarily unavailable

### ISSUE THREAD

**Issue by jakirkham** [jupyter/jupyter_console#33]
Related https://github.com/ipython/ipython/issues/7122
Related https://github.com/ipython/ipykernel/issues/79

I tried to reproduce this issue ( https://github.com/ipython/ipython/issues/7122 ) using `jupyter console`. However, I got this other unrelated issue instead.

Environment details.

    # packages in environment at /zopt/conda/envs/ipy:
    #
    appnope                   0.1.0                    py27_0    defaults
    decorator                 4.0.4                    py27_0    defaults
    ipykernel                 4.1.1                    py27_0    defaults
    ipython                   4.0.0                    py27_1    defaults
    ipython-genutils          0.1.0                     <pip>
    ipython_genutils          0.1.0                    py27_0    defaults
    jupyter-client            4.1.1                     <pip>
    jupyter-console           4.0.3                     <pip>
    jupyter-core              4.0.6                     <pip>
    jupyter_client            4.1.1                    py27_0    defaults
    jupyter_console           4.0.3                    py27_0    defaults
    jupyter_core              4.0.6                    py27_0    defaults
    numpy                     1.10.1                   py27_0    defaults
    openssl                   1.0.2d                        0    defaults
    path.py                   8.1.2                    py27_0    defaults
    pexpect                   3.3                      py27_0    defaults
    pickleshare               0.5                      py27_0    defaults
    pip                       7.1.2                    py27_0    defaults
    python                    2.7.10                        2    defaults
    python.app                1.2                      py27_4    defaults
    pyzmq                     14.7.0                   py27_1    defaults
    readline                  6.2                           2    <unknown>
    setuptools                18.4                     py27_0    defaults
    simplegeneric             0.8.1                    py27_0    defaults
    sqlite                    3.8.4.1                       1    <unknown>
    tk                        8.5.18                        0    <unknown>
    traitlets                 4.0.0                    py27_0    defaults
    wheel                     0.26.0                   py27_1    defaults
    zeromq                    4.1.3                         0    defaults
    zlib                      1.2.8                         0    <unknown>

Here's what happened.

    $ jupyter console
    Jupyter Console 4.0.3
    
    [ZMQTerminalIPythonApp] Loading IPython extension: storemagic
    [ZMQTerminalIPythonApp] Loading IPython extension: h5py.ipy_completer
    
    In [1]: from ipykernel.datapub import publish_data
    
    In [2]: import numpy as np
    
    In [3]: myarr = np.ones(2 * 1024 * 1024 * 1024 * 8 // 64)
    
    In [4]: publish_data({'x': myarr})
    Traceback (most recent call last):
      File "/zopt/conda/envs/nanshenv/bin/jupyter-console", line 5, in <module>
        app.main()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
        app.start()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/app.py", line 155, in start
        super(ZMQTerminalIPythonApp, self).start()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 353, in start
        self.shell.mainloop()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 420, in mainloop
        self.interact(display_banner=display_banner)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 588, in interact
        self.run_cell(source_raw)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 174, in run_cell
        self.handle_iopub(msg_id)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_console/interactiveshell.py", line 262, in handle_iopub
        sub_msg = self.client.iopub_channel.get_msg()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_client/blocking/channels.py", line 55, in get_msg
        return self._recv()
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/jupyter_client/blocking/channels.py", line 41, in _recv
        msg = self.socket.recv_multipart(**kwargs)
      File "/zopt/conda/envs/nanshenv/lib/python2.7/site-packages/zmq/sugar/socket.py", line 361, in recv_multipart
        part = self.recv(flags, copy=copy, track=track)
      File "zmq/backend/cython/socket.pyx", line 676, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6507)
      File "zmq/backend/cython/socket.pyx", line 710, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:6307)
      File "zmq/backend/cython/socket.pyx", line 147, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1877)
      File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6920)
        raise Again(errno)
    Again: Resource temporarily unavailable
    
    If you suspect this is an IPython bug, please report it at:
        https://github.com/ipython/ipython/issues
    or send an email to the mailing list at ipython-dev@scipy.org
    
    You can print a more detailed traceback right now with "%tb", or use "%debug"
    to interactively debug it.
    
    Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
        %config Application.verbose_crash=True

**Comment by takluyver** [comment]
This looks like an error coming from pyzmq. @minrk , any thoughts?

**Comment by minrk** [comment]
Could be a bug in pyzmq or libzmq. Looking into it now.

**Comment by minrk** [comment]
Yup, definitely a bug in either pyzmq or libzmq. Just deciding exactly what to do about it now.

The gist:

- zmq_msg APIs use an `int` returncode to signal success/failure. This used to be `0` or `-1`, but has since been modified to return the number of bytes sent/received on certain APIs.
- pyzmq checks `rc < 0`, which **should** indicate a failure to send
- since `rc` is a signed `int`, an overflow error occurs when the message is larger than `INT_MAX`, typically `2**31-1`, such that it will have a large negative value (`-(2**32 - size)`)

So there's a bug in libzmq that `rc` cannot represent sizes larger than INT_MAX, but it's a bug in a part of the zmq API that pyzmq doesn't actually care about (pyzmq uses other, non-problematic APIs to determine message size). I'll add a workaround in pyzmq (planning to release 15.2 tomorrow, anyway) to only check for `rc == -1`, which should allow this message to send and be received.

zeromq/pyzmq#782

**Comment by jakirkham** [comment]
Cool, thanks for looking into it and the explanation, @minrk.
