### ISSUE TITLE
AttributeError: module 'IPython.utils.rlineimpl' has no attribute 'set_completer_delims'

### ISSUE THREAD

**Issue by mikj** [jupyter/jupyter_console#36]
```
> jupyter console                                                                          
WARNING: Readline services not available or not loaded.                                    
Traceback (most recent call last):                                                         
  File "c:\program files\python 3.5\lib\runpy.py", line 170, in _run_module_as_main        
    "__main__", mod_spec)                                                                  
  File "c:\program files\python 3.5\lib\runpy.py", line 85, in _run_code                   
    exec(code, run_globals)                                                                
  File "C:\Program Files\Python 3.5\Scripts\jupyter-console.exe\__main__.py", line 9, in <m
odule>                                                                                     
    sys.exit(main())                                                                       
  File "c:\program files\python 3.5\lib\site-packages\jupyter_core\application.py", line 26
7, in launch_instance                                                                      
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)                     
  File "c:\program files\python 3.5\lib\site-packages\traitlets\config\application.py", lin
e 591, in launch_instance                                                                  
    app.initialize(argv)                                                                   
  File "c:\program files\python 3.5\lib\site-packages\jupyter_console\app.py", line 144, in
 initialize                                                                                
    super(ZMQTerminalIPythonApp, self).initialize(argv)                                    
  File "<decorator-gen-112>", line 2, in initialize                                        
  File "c:\program files\python 3.5\lib\site-packages\traitlets\config\application.py", lin
e 75, in catch_config_error                                                                
    return method(app, *args, **kwargs)                                                    
  File "c:\program files\python 3.5\lib\site-packages\IPython\terminal\ipapp.py", line 314,
 in initialize                                                                             
    self.init_shell()                                                                      
  File "c:\program files\python 3.5\lib\site-packages\jupyter_console\app.py", line 117, in
 init_shell                                                                                
    client=self.kernel_client,                                                             
  File "c:\program files\python 3.5\lib\site-packages\traitlets\config\configurable.py", li
ne 380, in instance                                                                        
    inst = cls(*args, **kwargs)                                                            
  File "c:\program files\python 3.5\lib\site-packages\IPython\core\interactiveshell.py", li
ne 543, in __init__                                                                        
    self.init_completer()                                                                  
  File "c:\program files\python 3.5\lib\site-packages\jupyter_console\interactiveshell.py",
 line 129, in init_completer                                                               
    self.Completer = ZMQCompleter(self, self.client, config=self.config)                   
  File "c:\program files\python 3.5\lib\site-packages\jupyter_console\completer.py", line 3
7, in __init__                                                                             
    self.readline.set_completer_delims('\r\n')                                             
AttributeError: module 'IPython.utils.rlineimpl' has no attribute 'set_completer_delims'   
                                                                                           
If you suspect this is an IPython bug, please report it at:                                
    https://github.com/ipython/ipython/issues                                              
or send an email to the mailing list at ipython-dev@scipy.org                              
                                                                                           
You can print a more detailed traceback right now with "%tb", or use "%debug"              
to interactively debug it.                                                                 
                                                                                           
Extra-detailed tracebacks for bug-reporting purposes can be enabled via:                   
    c.Application.verbose_crash=True                                                       

==============================================================================

> pip3 list                                    
decorator (4.0.6)                              
ipykernel (4.2.1)                              
ipython (4.0.1)                                
ipython-genutils (0.1.0)                       
ipywidgets (4.1.1)                             
Jinja2 (2.8)                                   
jsonschema (2.5.1)                             
jupyter (1.0.0)                                
jupyter-client (4.1.1)                         
jupyter-console (4.0.3)                        
jupyter-core (4.0.6)                           
MarkupSafe (0.23)                              
mistune (0.7.1)                                
nbconvert (4.1.0)                              
nbformat (4.0.1)                               
notebook (4.0.6)                               
path.py (8.1.2)                                
pickleshare (0.5)                              
pip (7.1.2)                                    
Pygments (2.0.2)                               
pyzmq (15.1.0)                                 
qtconsole (4.1.1)                              
setuptools (18.7.1)                            
simplegeneric (0.8.1)                          
tornado (4.3)                                  
traitlets (4.0.0)                              
```

**Comment by minrk** [comment]
Does it work if you do: `pip install pyreadine`?

**Comment by hoanglienson** [comment]
It works.
Thank you very much. ^^

**Comment by minrk** [comment]
We should fix the dependencies for this package to require pyreadline on Windows.
