### ISSUE TITLE
jupyter console crashing with scala211 kernel

### ISSUE THREAD

**Issue by sbromberger** [jupyter/jupyter_console#69]
Not sure where to go with this:

```
phase:scala me$ jupyter console --kernel scala211 --debug
[ZMQTerminalIPythonApp] Searching [u'/Users/me/dev/scala', '/Users/me/.jupyter', '/System/Library/Frameworks/Python.framework/Versions/2.7/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /System/Library/Frameworks/Python.framework/Versions/2.7/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /Users/me/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /Users/me/dev/scala
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /System/Library/Frameworks/Python.framework/Versions/2.7/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /Users/me/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /Users/me/dev/scala
[ZMQTerminalIPythonApp] Connection File not found: /Users/me/Library/Jupyter/runtime/kernel-32727.json
[ZMQTerminalIPythonApp] Found kernel julia-0.4 in /Users/me/Library/Jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel haskell in /Users/me/Library/Jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel javascript in /Users/me/Library/Jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel scala211 in /Users/me/.ipython/kernels
[ZMQTerminalIPythonApp] Native kernel (python2) available from /Users/me/Library/Python/2.7/lib/python/site-packages/ipykernel/resources
[ZMQTerminalIPythonApp] Starting kernel: [u'java', u'-jar', u'/Users/me/.ipython/kernels/scala211/launcher.jar', u'--quiet', u'--connection-file', u'/Users/me/Library/Jupyter/runtime/kernel-32727.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:55278
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:55275
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:55275
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:55276
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:55276
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:55277
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:55277
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:55279
Jupyter Console 4.1.1

[ZMQTerminalIPythonApp] Starting the jupyter console mainloop...

In [1]: val z = 5
WARNING: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.
z: Int = 5
Traceback (most recent call last):
  File "/Users/me/Library/Python/2.7/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/app.py", line 152, in start
    self.shell.mainloop()
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 483, in mainloop
    self.interact(display_banner=display_banner)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 659, in interact
    self.run_cell(source_raw)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 203, in run_cell
    self.handle_execute_reply(msg_id, timeout=0.05)
  File "/Users/me/Library/Python/2.7/lib/python/site-packages/jupyter_console/interactiveshell.py", line 221, in handle_execute_reply
    status = content['status']
KeyError: 'status'
```

Any ideas?

**Comment by takluyver** [comment]
Sounds like the kernel is sending an execute_reply message with the status field missing.

**Comment by sbromberger** [comment]
This is a kernel issue, then?

I'm getting `WARNING: The kernel did not respond to an is_complete_request. Setting `use_kernel_is_complete` to False.` on several kernels.

**Comment by sbromberger** [comment]
Ref: https://github.com/alexarchambault/jupyter-scala/issues/67

**Comment by takluyver** [comment]
That's a separate issue - `is_complete` messages were introduced more recently, and not all kernels support them, largely because they're not used in the notebook. The missing 'status' key is a bigger problem.

**Comment by sbromberger** [comment]
@takluyver thanks. I got this resolved - a fix was made to the kernel itself. Appreciate the guidance.
