### ISSUE TITLE
Running `vignette()` in R crashes the console

### ISSUE THREAD

**Issue by janschulz** [jupyter/jupyter_console#73]
```
c:\data\external\R
λ jupyter console --kernel ir33
Jupyter Console 4.1.1
[...]
In [4]: vignette()

Traceback (most recent call last):
  File "C:\portabel\miniconda\Scripts\jupyter-console-script.py", line 4, in <module>
    app.main()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\portabel\miniconda\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
    app.start()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\app.py", line 152, in start
    self.shell.mainloop()
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 483, in mainloop
    self.interact(display_banner=display_banner)
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 659, in interact
    self.run_cell(source_raw)
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 203, in run_cell
    self.handle_execute_reply(msg_id, timeout=0.05)
  File "C:\portabel\miniconda\lib\site-packages\jupyter_console\interactiveshell.py", line 231, in handle_execute_reply
    page.page(item['data']['text/plain'])
KeyError: 'data'
```

The notebook shows nothing (which is currently expected as we don#t have proper reprs installed for that)

**Comment by janschulz** [comment]
This is https://github.com/IRkernel/IRkernel/issues/328 in irkernel...

**Comment by takluyver** [comment]
Thanks @janschulz - we should indeed catch that.
