### ISSUE TITLE
Add --simple-prompt flag

### ISSUE THREAD

**Issue by dsblank** [jupyter/jupyter_console#93]
As mentioned https://github.com/ipython/ipython/issues/9758#issuecomment-232505670 jupyter_console needs a --simple-prompt flag to allow it to work inside other environments (eg, emacs).

**Comment by ajsteven130** [comment]
In emacs, people using jupyter console are using the jupyter_console_test environment variable to get simple-prompt behavior. It works well enough, but as this issue states, having the proper flag would be better. For an example, see jorgenschaefer/elpy#1041

Also, if we use exit() to close a session using the simple-prompt, we get the following error:

```
Traceback (most recent call last):
  File "/Users/avigan/anaconda/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/avigan/anaconda/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/avigan/anaconda/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/avigan/anaconda/lib/python3.5/site-packages/jupyter_console/app.py", line 151, in start
    self.shell.mainloop()
  File "/Users/avigan/anaconda/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 468, in mainloop
    self._eventloop.close()
AttributeError: 'NoneType' object has no attribute 'close'

Process Python exited abnormally with code 1
```

If the --simple-prompt flag makes it in to jypyter console, it may be good to sort out this error as well.

**Comment by takluyver** [comment]
#116 adds a flag and fixes the error on exit.
