### ISSUE TITLE
Crash with empty imput cells

### ISSUE THREAD

**Issue by mariusvniekerk** [jupyter/jupyter_console#94]
This seems to happen

```
In [2]:                                                                                     
Traceback (most recent call last):
  File "/home/mniekerk/miniconda3/envs/lab/bin/jupyter-console", line 6, in <module>
    sys.exit(jupyter_console.app.main())
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_console/app.py", line 151, in start
    self.shell.mainloop()
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 463, in mainloop
    self.interact()
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 448, in interact
    code = self.prompt_for_code()
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 408, in prompt_for_code
    reset_current_buffer=True)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in run
    t()
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 82, in read_from_stdin
    inputstream.feed(data)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 376, in feed
    self._input_parser.send(c)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 295, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 328, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 1006, in feed_key
    cli.input_processor.process_keys()
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 201, in process_keys
    self._process_coroutine.send(key_press)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 158, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 228, in _call_handler
    handler.call(event)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 31, in call
    return self.handler(event)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 342, in _
    more, indent = self.check_complete(d.text)
  File "/home/mniekerk/miniconda3/envs/lab/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 426, in check_complete
    more = (code.splitlines()[-1] != "")
IndexError: list index out of range
```

**Comment by takluyver** [comment]
Fixed, we hope, by #95.
